# Generated by Django 4.2 on 2026-04-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of period')),
                ('end_date', models.DateField(blank=True, help_text='Last day of period', null=True)),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='moderate', help_text='Intensity of menstrual flow', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Period Cycle',
                'verbose_name_plural': 'Period Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(choices=[('cramps', 'Cramps'), ('headache', 'Headache'), ('bloating', 'Bloating'), ('fatigue', 'Fatigue'), ('mood_swings', 'Mood Swings'), ('breast_tenderness', 'Breast Tenderness'), ('acne', 'Acne'), ('nausea', 'Nausea'), ('back_pain', 'Back Pain'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('logged_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='tracker.periodcycle')),
            ],
            options={
                'verbose_name': 'Health Symptom',
                'verbose_name_plural': 'Health Symptoms',
                'ordering': ['logged_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cycle_length', models.IntegerField(default=28, help_text='Average cycle length in days')),
                ('average_period_length', models.IntegerField(default=5, help_text='Average period duration in days')),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle Reminder',
                'verbose_name_plural': 'Cycle Reminders',
            },
        ),
    ]
