# Generated by Django 4.2 on 2026-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('period_reminder_3days', 'Period Reminder - 3 Days Before'), ('period_reminder_today', 'Period Reminder - Today'), ('period_late_alert', 'Late Period Alert'), ('symptom_reminder', 'Symptom Reminder'), ('cycle_prediction', 'Cycle Prediction')], default='period_reminder_3days', max_length=30),
        ),
    ]
