# Generated by Django 4.2.30 on 2026-04-19 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Google OAuth access token')),
                ('refresh_token', models.TextField(help_text='Google OAuth refresh token')),
                ('token_expiry', models.DateTimeField(help_text='Token expiration datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_id', models.CharField(help_text='Google Calendar event ID', max_length=255)),
                ('reminder_date', models.DateField(help_text='Date of the reminder (1 day before period start)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_reminder', to='tracker.periodcycle')),
            ],
            options={
                'verbose_name': 'Google Calendar Reminder',
                'verbose_name_plural': 'Google Calendar Reminders',
            },
        ),
    ]
